### ISSUE TITLE
Instalation steps

### ISSUE THREAD

**Issue by nicolasflorth** [storesbuzz/laravel-multiAuth#1]
Hi!
Can you add some installation steps, please?
I installed composer, migrated the tables, but I have files missing, like a public/index.php
...maybe other files too

Is any other command that I need to run?
Thanks!

**Comment by storesbuzz** [comment]
Hi @nicolasflorth , I have index.php out of the public folder in order to remove public from url. You should test without public in URL. Also, you must add the following code to your .htaccess file to avoiod public visibility of .env file data.

```
    # Hide a specific file
    <Files .env>
        Order allow,deny
        Deny from all
    </Files>
    Options All Indexes
```
